#!/bin/bash

usage() {
	echo "Usage: $0 test_number num_threads|p"
	exit 1
}

if [ "$1" == "clean" ]; then
	rm output_test_* gmon.out 2> /dev/null
	make clean
	exit
fi

if [ "$#" -lt "2" ]; then
	usage
fi

if [ "$2" == "p" ]; then
	make gprof
else
	make
fi

#L    largura da matriz
#A    altura da matriz
#J    número de joaninhas
#s    semente para o gerador aleatório
#C    constante de emissão de calor da joaninha
#Tmin menor temperatura que a joaninha considera confortável
#Tmax maior temperatura que a joaninha considera confortável
#pc   probabilidade, por hexágono, de aparecer uma fonte de calor
#nc   duração em ciclos da fonte de calor
#pf   probabilidade, por hexágono, de aparecer uma fonte de frio
#nf   duração em ciclos da fonte de frio
#T    número de ciclos de simulação
#P    número de processadores (threads) para execução

echo -e "\e[1;31mTime:\e[0m"
case "$1" in
"1")
#                L A  J  s       C   Tmin Tmax pc   nc pf  nf T     P
time ./joaninhas 8 10 10 1000000 1.5 6.0  9.0  0.08 2  0.1 2  10000 $2 > output_test_1
;;

"2")
#                L   A   J  s       C      Tmin  Tmax  pc    nc pf   nf T     P
time ./joaninhas 100 100 30 1000000 22.765 18.00 27.00 0.025 2  0.04 4  10000 $2 > output_test_2
;;

"3")
#                L   A   J   s       C      Tmin  Tmax  pc    nc pf   nf T     P
time ./joaninhas 100 100 100 1000000 22.765 18.00 27.00 0.025 2  0.04 4  10000 $2 > output_test_3
;;

"4")
#                L   A   J    s       C      Tmin  Tmax  pc   nc pf  nf T     P
time ./joaninhas 100 100 1000 1000000 22.765 18.00 27.00 0.1  30 0.1 40 10000 $2 > output_test_4
;;

"5")
#                L   A   J  s       C      Tmin  Tmax  pc   nc pf  nf T     P
time ./joaninhas 100 100 10 1000000 22.765 18.00 27.00 0.1  30 0.1 40 10000 $2 > output_test_5
;;

"6")
#                L   A   J   s       C      Tmin  Tmax  pc   nc pf  nf T     P
time ./joaninhas 100 100 100 1000000 22.765 18.00 27.00 0.1  30 0.1 40 10000 $2 > output_test_6
;;

esac

if [ "$2" == "p" ]; then
	echo -e "\n\n\n\e[1;31mProfiling:\e[0m"
	gprof -bp joaninhas
fi
